# Generated by Django 5.0.6 on 2024-06-09 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_date_joined_user_date_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
    ]
